if(NOT "${PROJECT_NAME}" STREQUAL "cxxblas")
  set(CXXBLAS_NO_EXAMPLES 1)
  set(CXXBLAS_DIR "${CMAKE_CURRENT_LIST_DIR}/..")
  add_subdirectory(${CXXBLAS_DIR})
  
  get_directory_property(CXXBLAS_INCLUDE_DIR DIRECTORY ${CXXBLAS_DIR} DEFINITION CXXBLAS_INCLUDE_DIR)
  get_directory_property(CXXBLAS_LIBRARIES DIRECTORY ${CXXBLAS_DIR} DEFINITION CXXBLAS_LIBRARIES)
  
  include_directories(${CXXBLAS_INCLUDE_DIR})
endif()
